{{- $chartName := include "mc-cookbook.name" . -}}
{{- $tracingUrl := include "mc-cookbook.tracingUrl" . -}}
{{- $metricsUrl := include "mc-cookbook.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  PYCSW-RASTER-SERVICE_URL: {{ quote .Values.env.PYCSW_RASTER_SERVICE_URL }}
  PYCSW-3D-SERVICE_URL: {{ quote .Values.env.PYCSW_3D_SERVICE_URL}}
  PYCSW-DEM-SERVICE_URL: {{ quote .Values.env.PYCSW_DEM_SERVICE_URL }}
  MAP_SERVER-RASTER-SERVICE_URL: {{ quote .Values.env.MAP_SERVER_RASTER_SERVICE_URL }}
  MAP_SERVER-DEM-SERVICE_URL: {{ quote .Values.env.MAP_SERVER_DEM_SERVICE_URL }}
  CLASSIFIED_REPO_URL: {{ quote .Values.env.CLASSIFIED_REPO_URL }}

{{- end }}
