{{- $chartName := include "developer-portal.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  PLAYGROUND_URL: {{ quote .Values.env.PLAYGROUND_URL }}
  PUZZLE_URL: {{ quote .Values.env.PUZZLE_URL }}
  CATALOG_APPLICATION_URL: {{ quote .Values.env.CATALOG_APPLICATION_URL }}
  npm_config_cache: /tmp/

{{- end }}
