apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookbook-deployment
  namespace: default
  labels:
    app: cookbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookbook
  template:
    metadata:
      labels:
        app: cookbook
    spec:
      containers:
      - name: cookbook
        image: mc-cookbook:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
            limits:
              memory: 200Mi
              cpu: "1"
        
---
apiVersion: v1
kind: Service
metadata:
  name: cookbook-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: cookbook
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001