global:
  cloudProvider: {}
  environment: {}
enabled: true
environment: production
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030
resetOnConfigChange: true
cloudProvider:
  imagePullSecretName: my-registry-secret
  flavor: openshift
image:
  repository: developer-portal
  tag: v3.0.1
  imagePullPolicy: IfNotPresent
env:
  port: 8080
  targetPort: 8080
  PLAYGROUND_URL: https://PLAYGROUND_URL.com
  PUZZLE_URL: https://PUZZLE_URL.com
  CATALOG_APPLICATION_URL: https://CATALOG_APPLICATION_URL.com
  YAHALOM_APPLICATION_URL: https://placeholder.com
resources:
  enabled: true
  value:
    limits:
      cpu: 250m
      memory: 64Mi
    requests:
      cpu: 250m
      memory: 64Mi
route:
  enabled: false
  https: true
  path: /
  host: some-host
  wildcardPolicy: None
  port:
    targetPort: YOUR-SERVICE-EXPOSED-PORT
  tls:
    termination: edge
    certificate: THE-CONTENT-OF-THE-CERT-FILE
    key: THE-CONTENT-OF-THE-KEY-FILE
    caCertificate: THE-CONTENT-OF-THE-ROOT-CA-FILE
    insecureEdgeTerminationPolicy: Redirect # <- important
  timeout:
    enabled: false
    duration: 60s
ingress:
  enabled: true
  path: /
  host: localhost
  cors:
    enabled: true
    origin: '*'
