global:
  cloudProvider: {}
  environment: {}
enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030
resetOnConfigChange: true
cloudProvider:
  dockerRegistryUrl: localhost:5001
  imagePullSecretName: my-registry-secret
  flavor: openshift
caSecretName: ''
caPath: /usr/local/share/ca-certificates
caKey: ca.crt
image:
  repository: developer-portal
  tag: v1.0.2
  imagePullPolicy: IfNotPresent
env:
  port: 80
  targetPort: 8080
  RASTER_CATALOG_SERVICE_URL: "https://pycsw_raster.com"
  RASTER_EXPORT_SERVICE_URL: "https://export_raster.com"
  RASTER-RASTER-SERVING-SERVICE_URL: "https://map-server_raster.com"
  3D_CATALOG_SERVICE_URL: "https://pycsw_3d.com"
  3D_MODEL_SERVING_SERVICE_URL: "https://3d_model_server.com"
  DEM_CATALOG_SERVICE_URL: "https://pycsw_dem.com"
  DEM_DEM_SERVING_SERVICE_URL: "https://map-server_dem.com"
  DEM_SUPERIOR_SERVICE_URL: "https://dem_superior_service.com"
  VECTOR_QUERY_SERVICE_URL: "https://wfs.com"
  VECTOR_REPLICATION_SERVICE_URL: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  APP_CATALOG_URL: "http://catalog_app.com"
  API_KEY: "API_KEY"
  EMOJI_CODE: "false"
  INJECTION_TYPE: "queryParam"
  CLASSIFIED_REPO_URL: "https://github.com/MapColonies/docs-test.git"
resources:
  enabled: true
  value:
    limits:
      cpu: 250m
      memory: 64Mi
    requests:
      cpu: 500m
      memory: 128Mi
route:
  enabled: true
  https: true
  path: /
  timeout:
    enabled: false
    duration: 60s
ingress:
  enabled: false
  path: /
  host: localhost
  cors:
    enabled: true
    origin: '*'
