global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}
enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030
resetOnConfigChange: true
cloudProvider:
  dockerRegistryUrl: localhost:5001
  imagePullSecretName: my-registry-secret
  flavor: openshift
caSecretName: ''
caPath: /usr/local/share/ca-certificates
caKey: ca.crt
image:
  repository: mc-cookbook
  tag: v1.0.2
  imagePullPolicy: IfNotPresent
env:
  port: 80
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: 'http://localhost:55681/v1/trace'
  metrics:
    enabled: false
    url: 'http://localhost:55681/v1/metrics'
  PYCSW_RASTER_SERVICE_URL: "https://pycsw_raster.com"
  PYCSW_3D_SERVICE_URL: "https://pycsw_3d.com"
  PYCSW_DEM_SERVICE_URL: "https://pycsw_dem.com"
  MAP_SERVER_RASTER_SERVICE_URL: "https://map-server_raster.com"
  MAP_SERVER_DEM_SERVICE_URL: "https://map-server_dem.com"
  WFS_VECTOR_SERVICE_URL: "https://wfs.com"
  CLASSIFIED_REPO_URL: "https://github.com/MapColonies/docs-test.git"
  REPLICATION_VECTOR_SERVICE_URL: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  API_KEY: "API_KEY"
  EMOJI_CODE: "false"
  MODEL_SERVER_3D_SERVICE_URL: "https://3d_model_server.com"
  SUPERIOR_DEM_SERVICE_URL: "https://dem_superior_service.com"
resources:
  enabled: false
  value:
    limits:
      cpu: 500m
      memory: 900Mi
    requests:
      cpu: 500m
      memory: 900Mi
route:
  enabled: true
  path: /
  timeout:
    enabled: false
    duration: 60s
ingress:
  enabled: false
  path: /
  host: localhost
  cors:
    enabled: true
    origin: '*'
