name: Test deployment

on:
  pull_request:
    branches: [master]

env:
  PUZZLE_URL: https://cptschnitz.github.io/map-tile-puzzle/
  CATALOG_APPLICATION_URL: https://github.com/MapColonies
  PLAYGROUND_URL: https://sandcastle.cesium.com/
  BASE_URL: '/developer-portal/'

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build